require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'gems/**/*'
    - 'node_modules/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/environments/*'
    - 'app/controllers/users/*'
    - 'app/controllers/application_controller.rb'
  NewCops: enable

Rails:
  Enabled: true

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Security:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
