version: "3"
volumes:
  mysql_data:
  public_data:
  tmp_data:
  gem_data:

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/cafeapp
      - /cafeapp/log
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    tty: true
    stdin_open: true
    command: bundle exec rails server -p 3000 -b 0.0.0.0
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - gem_data:/usr/local/bundle
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public_data:/cafeapp/public
      - tmp_data:/cafeapp/tmp
    ports:
      - '80:80'
    depends_on:
      - app
