version: "3"
volumes:
  public_data:
  tmp_data:
  gem_data:
  log_data:

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/cafeapp
      - public_data:/cafeapp/public
      - gem_data:/usr/local/bundle
      - log_data:/var/log/nginx
      - tmp_data:/cafeapp/tmp
    environment:
      - TZ='Asia/Tokyo'
    tty: true
    stdin_open: true
    command: bundle exec rails server -e production
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public_data:/cafeapp/public
      - tmp_data:/cafeapp/tmp
    ports:
      - '80:80'
    depends_on:
      - app
