version: "3"
volumes:
  mysql_data:
  public_data:
  tmp_data:
  gem_data:

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/cafeapp
      - gem_data:/usr/local/bundle
      - /cafeapp/log
    environment:
      - TZ='Asia/Tokyo'
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: bundle exec rails server -p 3000 -b 0.0.0.0
  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/cafeapp
      - gem_data:/usr/local/bundle
    ports:
      - '127.0.0.1:3035:3035'
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - gem_data:/usr/local/bundle
    environment:
      TZ: 'Asia/Tokyo'
    env_file:
      - .env
    ports:
      - '3306:3306'
  web:
    build:
      context: ./nginx_docker
    volumes:
      - public_data:/cafeapp/public
      - tmp_data:/cafeapp/tmp
    ports:
      - '80:80'
    depends_on:
      - app
